# Generated by Django 5.0.6 on 2024-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0002_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='Top Wear', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='sub_category',
            field=models.CharField(default='T-Shirt', max_length=100),
        ),
    ]
