# Generated by Django 5.0.6 on 2024-07-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0002_remove_product_price_product_discount_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
