# Generated by Django 5.0.6 on 2024-08-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0002_order_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
