# Generated by Django 5.0.6 on 2024-07-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0004_items_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10, null=True),
        ),
    ]
