# Generated by Django 5.0.6 on 2024-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0004_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='brand',
            field=models.CharField(default='Gucci', max_length=50),
        ),
        migrations.AddField(
            model_name='userorder',
            name='size',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
