# Generated by Django 5.0.6 on 2024-07-19 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0005_items_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myeSite.items')),
            ],
        ),
    ]
