# Generated by Django 5.0.6 on 2024-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0005_userorder_brand_userorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='billing_add',
            field=models.CharField(default='Biratnagar', max_length=100),
        ),
        migrations.AddField(
            model_name='userorder',
            name='shipping_add',
            field=models.CharField(default='Biratnagar', max_length=100),
        ),
    ]
