# Generated by Django 5.0.6 on 2024-07-29 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0005_alter_wishlist_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
