# Generated by Django 5.0.6 on 2024-07-29 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0006_alter_wishlist_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 16, 56, 26, 401168, tzinfo=datetime.timezone.utc)),
        ),
    ]
