# Generated by Django 5.0.6 on 2024-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0006_itemsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(default='Gucci', max_length=100),
        ),
    ]
