# Generated by Django 5.0.6 on 2024-08-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0007_alter_userorder_billing_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='billing_add',
            field=models.CharField(default='brt', max_length=100),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_add',
            field=models.CharField(default='drn', max_length=100),
        ),
    ]
