# Generated by Django 5.0.6 on 2024-07-31 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0008_alter_wishlist_added_date_cartsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 13, 33, 16, 830785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='myeSite.size'),
        ),
    ]
