# Generated by Django 5.0.6 on 2024-09-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0008_alter_userorder_billing_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isnew',
            field=models.BooleanField(default=True),
        ),
    ]
