# Generated by Django 5.0.6 on 2024-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0009_alter_usertable_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=10, null=True),
        ),
    ]
