# Generated by Django 5.0.6 on 2024-07-31 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0009_size_alter_wishlist_added_date_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='myeSite.size'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 13, 57, 28, 928350, tzinfo=datetime.timezone.utc)),
        ),
    ]
