# Generated by Django 5.0.6 on 2024-09-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0009_product_isnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isnew',
            field=models.BooleanField(default=False),
        ),
    ]
