# Generated by Django 5.0.6 on 2024-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0010_items_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=50),
        ),
    ]
