# Generated by Django 5.0.6 on 2024-09-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='heart_count',
        ),
    ]
