# Generated by Django 5.0.6 on 2024-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0013_remove_review_heart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='361SVT', max_length=8, null=True),
        ),
    ]
