# Generated by Django 5.0.6 on 2024-09-16 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0014_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='size',
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(default='M', max_length=50)),
                ('brand', models.CharField(default='Gucci', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myeSite.userorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeSite.product')),
            ],
        ),
    ]
