# Generated by Django 5.0.6 on 2024-09-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0015_remove_userorder_brand_remove_userorder_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='contact',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='userorder',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
