# Generated by Django 5.0.6 on 2024-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0015_price_remove_wishlistitem_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='items',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='price',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10, null=True),
        ),
    ]
