# Generated by Django 5.0.6 on 2024-08-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0016_shippingoption_alter_shippingaddress_shipping_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_option',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='product_title',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myeSite.product'),
        ),
        migrations.DeleteModel(
            name='ShippingOption',
        ),
    ]
