# Generated by Django 5.0.6 on 2024-07-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0016_remove_items_discount_amount_remove_items_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='items',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
