# Generated by Django 5.0.6 on 2024-09-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0016_userorder_contact_userorder_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='contact',
        ),
        migrations.AlterField(
            model_name='userorder',
            name='contact_number',
            field=models.CharField(default='9898989898', max_length=14),
        ),
    ]
