# Generated by Django 5.0.6 on 2024-08-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0017_alter_shippingaddress_shipping_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='qty',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='billing_address',
            field=models.ForeignKey(default='Brt', on_delete=django.db.models.deletion.CASCADE, to='myeSite.billingaddress'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='shipping_address',
            field=models.ForeignKey(default='Brt', on_delete=django.db.models.deletion.CASCADE, to='myeSite.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
