# Generated by Django 5.0.6 on 2024-09-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0017_remove_userorder_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='shipping_city',
            field=models.CharField(default='drn', max_length=100),
        ),
    ]
