# Generated by Django 5.0.6 on 2024-07-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0017_alter_items_price_items_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='items',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=10, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='myeSite.items')),
            ],
        ),
    ]
