# Generated by Django 5.0.6 on 2024-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0018_userorder_shipping_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='shipping_option',
            field=models.CharField(default='standard', max_length=100),
        ),
    ]
