# Generated by Django 5.0.6 on 2024-08-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0018_remove_ordertable_qty_ordertable_billing_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
