# Generated by Django 5.0.6 on 2024-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0020_userorder_billing_city_userorder_fullname_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, default='search_keyword_here', max_length=100, null=True),
        ),
    ]
