# Generated by Django 5.0.6 on 2024-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0023_shippingoption_alter_shippingaddress_shipping_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_option',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ShippingOption',
        ),
    ]
