# Generated by Django 5.0.6 on 2024-09-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0023_productsalesrecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
