# Generated by Django 5.0.6 on 2024-09-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0024_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
