# Generated by Django 5.0.6 on 2024-08-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0025_ordertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
