# Generated by Django 5.0.6 on 2024-09-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeSite', '0026_userorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsalesrecord',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=15, null=True),
        ),
    ]
